name: 'Self hosted runner workspace cleaner'
description: 'Workflow cleanup when using a self hosted Github Actions runner'
runs:
  using: "composite"
  steps:
    - run: |
        rm -rf "${{ github.workspace }}"
        mkdir -p "${{ github.workspace }}"
        echo "Cleaned up previous run"
      shell: bash

    - run: |
        if [ -f "/home/runner/.ssh/id_rsa" ]; then rm /home/runner/.ssh/id_rsa; fi
        rm -rf $HOME/.ssh
        echo "Cleaned up $HOME/.ssh"
      shell: bash
